### ISSUE TITLE
Prod vs Dev mongoDB connections

### ISSUE THREAD

**Issue by shaaddev** [TechWise-Project-2/ProductivityTracker#23]
Hey, can you add this line of code to line 10 and line 135 for the connection of mongoose.

`process.env.MODE === "prod" ? process.env.PROD : process.env.DEV`

both lines should be `mongoose.connect(process.env.DEV)` and `mongoose.createConnection(process.env.DEV)`, respectively.

Regards,

**Comment by rukaiah-edhah** [comment]
Done.
